/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// CatalogApiService is a service that implents the logic for the CatalogApiServicer
// This service should implement the business logic for every endpoint for the CatalogApi API. 
// Include any external packages or services that will be required by this service.
type CatalogApiService struct {
}

// NewCatalogApiService creates a default api service
func NewCatalogApiService() CatalogApiServicer {
	return &CatalogApiService{}
}

// CatalogGet - get the catalog of services that the service broker offers
func (s *CatalogApiService) CatalogGet(xBrokerAPIVersion string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string) (interface{}, error) {
	// TODO - update CatalogGet with the required logic for this service method.
	// Add api_catalog_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'CatalogGet' not implemented")
}
