/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// ServiceBindingsApiService is a service that implents the logic for the ServiceBindingsApiServicer
// This service should implement the business logic for every endpoint for the ServiceBindingsApi API. 
// Include any external packages or services that will be required by this service.
type ServiceBindingsApiService struct {
}

// NewServiceBindingsApiService creates a default api service
func NewServiceBindingsApiService() ServiceBindingsApiServicer {
	return &ServiceBindingsApiService{}
}

// ServiceBindingBinding - generation of a service binding
func (s *ServiceBindingsApiService) ServiceBindingBinding(xBrokerAPIVersion string, instanceId string, bindingId string, body ServiceBindingRequest, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (interface{}, error) {
	// TODO - update ServiceBindingBinding with the required logic for this service method.
	// Add api_service_bindings_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceBindingBinding' not implemented")
}

// ServiceBindingGet - gets a service binding
func (s *ServiceBindingsApiService) ServiceBindingGet(xBrokerAPIVersion string, instanceId string, bindingId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, serviceId string, planId string) (interface{}, error) {
	// TODO - update ServiceBindingGet with the required logic for this service method.
	// Add api_service_bindings_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceBindingGet' not implemented")
}

// ServiceBindingLastOperationGet - last requested operation state for service binding
func (s *ServiceBindingsApiService) ServiceBindingLastOperationGet(xBrokerAPIVersion string, instanceId string, bindingId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, serviceId string, planId string, operation string) (interface{}, error) {
	// TODO - update ServiceBindingLastOperationGet with the required logic for this service method.
	// Add api_service_bindings_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceBindingLastOperationGet' not implemented")
}

// ServiceBindingUnbinding - deprovision of a service binding
func (s *ServiceBindingsApiService) ServiceBindingUnbinding(xBrokerAPIVersion string, instanceId string, bindingId string, serviceId string, planId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (interface{}, error) {
	// TODO - update ServiceBindingUnbinding with the required logic for this service method.
	// Add api_service_bindings_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceBindingUnbinding' not implemented")
}
