/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// ServiceInstancesApiService is a service that implents the logic for the ServiceInstancesApiServicer
// This service should implement the business logic for every endpoint for the ServiceInstancesApi API. 
// Include any external packages or services that will be required by this service.
type ServiceInstancesApiService struct {
}

// NewServiceInstancesApiService creates a default api service
func NewServiceInstancesApiService() ServiceInstancesApiServicer {
	return &ServiceInstancesApiService{}
}

// ServiceInstanceDeprovision - deprovision a service instance
func (s *ServiceInstancesApiService) ServiceInstanceDeprovision(xBrokerAPIVersion string, instanceId string, serviceId string, planId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (interface{}, error) {
	// TODO - update ServiceInstanceDeprovision with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceInstanceDeprovision' not implemented")
}

// ServiceInstanceGet - gets a service instance
func (s *ServiceInstancesApiService) ServiceInstanceGet(xBrokerAPIVersion string, instanceId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, serviceId string, planId string) (interface{}, error) {
	// TODO - update ServiceInstanceGet with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceInstanceGet' not implemented")
}

// ServiceInstanceLastOperationGet - last requested operation state for service instance
func (s *ServiceInstancesApiService) ServiceInstanceLastOperationGet(xBrokerAPIVersion string, instanceId string, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, serviceId string, planId string, operation string) (interface{}, error) {
	// TODO - update ServiceInstanceLastOperationGet with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceInstanceLastOperationGet' not implemented")
}

// ServiceInstanceProvision - provision a service instance
func (s *ServiceInstancesApiService) ServiceInstanceProvision(xBrokerAPIVersion string, instanceId string, body ServiceInstanceProvisionRequest, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (interface{}, error) {
	// TODO - update ServiceInstanceProvision with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceInstanceProvision' not implemented")
}

// ServiceInstanceUpdate - update a service instance
func (s *ServiceInstancesApiService) ServiceInstanceUpdate(xBrokerAPIVersion string, instanceId string, body ServiceInstanceUpdateRequest, xBrokerAPIOriginatingIdentity string, xBrokerAPIRequestIdentity string, acceptsIncomplete bool) (interface{}, error) {
	// TODO - update ServiceInstanceUpdate with the required logic for this service method.
	// Add api_service_instances_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ServiceInstanceUpdate' not implemented")
}
